# Wrapper around 'devcontainer features test'.
#
# The CLI has no config file for its defaults, so the base image and the flags
# that would otherwise be retyped every run live here. See the README for what
# each combination actually runs.

BASE_IMAGE   ?= mcr.microsoft.com/devcontainers/base:ubuntu
REMOTE_USER  ?=
DEVCONTAINER ?= devcontainer
NAMESPACE    ?= congealer/devcon-features

FEATURES := $(notdir $(wildcard src/*))
TEST     := $(DEVCONTAINER) features test -p .
USER_OPT := $(if $(REMOTE_USER),-u $(REMOTE_USER),)

# Base images pulled by the CI matrix and by the scenarios. Removed by
# 'clean-all' only, since re-pulling them is slow.
BASE_IMAGES := ubuntu:focal ubuntu:latest debian:latest \
	mcr.microsoft.com/devcontainers/base:ubuntu \
	mcr.microsoft.com/devcontainers/base:debian

# Images left behind by a test run. They are named vsc-<timestamp>-<sha>-features
# and the CLI never removes them. Matching on the timestamp is what keeps this
# from touching dev container images, which are named after their folder
# (vsc-<folder>-<sha>-features).
TEST_IMAGE := ^vsc-[0-9]{10,}-[0-9a-f]{32,}-features(-uid)?:

# Catch a mistyped feature name here instead of letting the CLI fail on it.
define require-feature
@echo "$(FEATURES)" | grep -qw "$(1)" \
	|| { echo "unknown feature '$(1)'. available: $(FEATURES)" >&2; exit 1; }
endef

.DEFAULT_GOAL := help
.PHONY: help test test-global docs clean distclean

help:  ## Show this help
	@grep -hE '^[a-z][a-z%-]*:.*##' $(MAKEFILE_LIST) | sed -E 's/:[^#]*## /\t/' | expand -t 16
	@echo
	@echo "features:   $(FEATURES)"
	@echo "BASE_IMAGE: $(BASE_IMAGE)"

test:  ## Every feature, its scenarios, and the global scenarios
	$(TEST) -i $(BASE_IMAGE) $(USER_OPT)

# An explicit rule wins over a pattern rule in GNU make, so this is not
# swallowed by 'test-%' below.
test-global:  ## The scenarios under test/_global only
	$(TEST) --global-scenarios-only

test-%:  ## One feature: test.sh, its scenarios and duplicate.sh
	$(call require-feature,$*)
	$(TEST) -f $* -i $(BASE_IMAGE) $(USER_OPT)

unit-%:  ## One feature: test.sh only
	$(call require-feature,$*)
	$(TEST) -f $* -i $(BASE_IMAGE) $(USER_OPT) --skip-scenarios

scenario-%:  ## One feature: its scenarios only
	$(call require-feature,$*)
	$(TEST) -f $* --skip-autogenerated --skip-duplicated

# '-p' wants the directory the Features live *in*, not the project root the
# other commands take. There is no way to regenerate a single Feature: whatever
# is passed to '-p' is scanned for children, so this always rewrites all four.
docs:  ## Regenerate every src/<feature>/README.md from its metadata and NOTES.md
	$(DEVCONTAINER) features generate-docs -p src -n $(NAMESPACE) \
	    --github-owner $(word 1,$(subst /, ,$(NAMESPACE))) \
	    --github-repo $(word 2,$(subst /, ,$(NAMESPACE)))

# Publishes with your own credentials rather than through the release
# workflow. A version that is already published is skipped, so this uploads
# whatever Feature had its version bumped and nothing else.
#
# Publishing 1.3.0 also moves the '1', '1.3' and 'latest' tags onto it, which
# is what anyone pinned to ':1' picks up on their next build.
release:  ## Publish every Feature under src/ to GHCR
	@gh auth status > /dev/null 2>&1 \
	    || { echo "gh is not logged in - run 'gh auth login'"; exit 1; }
	GITHUB_TOKEN=$$(gh auth token) $(DEVCONTAINER) features publish \
	    -r ghcr.io -n $(NAMESPACE) ./src

clean:  ## Remove the containers, images and build cache the tests leave behind
	@docker ps -a --format '{{.ID}} {{.Image}}' | grep -E ' vsc-[0-9]{10,}' \
	    | cut -d' ' -f1 | xargs -r docker rm -f
	@docker images --format '{{.Repository}}:{{.Tag}}' | grep -E '$(TEST_IMAGE)' \
	    | xargs -r docker rmi -f
	@docker builder prune -f

distclean: clean  ## Also drop the base images and the whole build cache
	@docker rmi -f $(BASE_IMAGES) 2>/dev/null || true
	@docker builder prune -af
